version: "3.8"

services:
  db:
    image: postgres:13
    container_name: work_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=work_db_user
      - POSTGRES_PASSWORD=DPE@013455dgvdfg491!qwerty
      - POSTGRES_DB=work_db
    restart: always

  web:
    build: .
    container_name: work_server
    command: sh -c "
      python manage.py makemigrations user &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
